src/Entity/Bird.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BirdRepository")
 */
class Bird
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reign;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phylum;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $class;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $bird_order;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $family;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $vernacularname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $validname;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Image", orphanRemoval=true)
     * @ORM\JoinColumn(nullable=true)
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Capture", mappedBy="bird", orphanRemoval=true)
     */
    private $captures;

    public function __construct()
    {
        $this->captures = new ArrayCollection();
    }

    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return null|string
     */
    public function getReign(): ?string
    {
        return $this->reign;
    }

    /**
     * @param string $reign
     * @return Bird
     */
    public function setReign(string $reign): self
    {
        $this->reign = $reign;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getPhylum(): ?string
    {
        return $this->phylum;
    }

    /**
     * @param string $phylum
     * @return Bird
     */
    public function setPhylum(string $phylum): self
    {
        $this->phylum = $phylum;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getClass(): ?string
    {
        return $this->class;
    }

    /**
     * @param string $class
     * @return Bird
     */
    public function setClass(string $class): self
    {
        $this->class = $class;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getBirdOrder(): ?string
    {
        return $this->bird_order;
    }

    /**
     * @param string $bird_order
     * @return Bird
     */
    public function setBirdOrder(string $bird_order): self
    {
        $this->bird_order = $bird_order;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getFamily(): ?string
    {
        return $this->family;
    }

    /**
     * @param string $family
     * @return Bird
     */
    public function setFamily(string $family): self
    {
        $this->family = $family;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getVernacularname(): ?string
    {
        return $this->vernacularname;
    }

    /**
     * @param string $vernacularname
     * @return Bird
     */
    public function setVernacularname(string $vernacularname): self
    {
        $this->vernacularname = $vernacularname;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getValidname(): ?string
    {
        return $this->validname;
    }

    /**
     * @param string $validname
     * @return Bird
     */
    public function setValidname(string $validname): self
    {
        $this->validname = $validname;

        return $this;
    }

    /**
     * @param Image|null $image
     */
    public function setImage(Image $image = null)
    {
        $this->image = $image;
    }

    /**
     * @return mixed
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @return Collection|Capture[]
     */
    public function getCaptures(): Collection
    {
        return $this->captures;
    }

    /**
     * @param Capture $capture
     * @return Bird
     */
    public function addCapture(Capture $capture): self
    {
        $this->captures[] = $capture;
        
        $capture->setBird($this);

        return $this;
    }

    /**
     * @param Capture $capture
     * @return Bird
     */
    public function removeCapture(Capture $capture): self
    {
        $this->captures->removeElement($capture);
    }
}

src/Controller/Frontend/BirdController.php
<?php

namespace App\Controller\Frontend;

use App\Entity\Bird;
use App\Services\Bird\NAOBirdManager;
use App\Services\Bird\NAOCountBirds;
use App\Services\Pagination\NAOPagination;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class BirdController extends Controller
{
    /**
     * @Route("repertoire/{letter}/{page}", defaults={"page"=1}, requirements={"page" = "\d+"}, name="repertory_by_letter")
     * @param $letter
     * @param NAOBirdManager $naoBirdManager
     * @param NAOPagination $naoPagination
     * @param NAOCountBirds $naoCountBirds
     * @param $page
     * @return Response
     */
    public function showRepertoryByLetter($letter, NAOBirdManager $naoBirdManager, NAOPagination $naoPagination, NAOCountBirds $naoCountBirds, $page)
    {
        $numberOfBirds = $naoCountBirds->countBirdsByLetter($letter);
        $numberOfBirdsPerPage = $naoPagination->getNbBirdsPerPage();
        $birds = $naoBirdManager->getBirdsByLetter($letter, $page, $numberOfBirds, $numberOfBirdsPerPage);
        $nbRepertoryPages = $naoPagination->CountNbPages($numberOfBirds, $numberOfBirdsPerPage);
        $nextPage = $naoPagination->getNextPage($page);
        $previousPage = $naoPagination->getPreviousPage($page);
        $regions = json_decode(file_get_contents("https://geo.api.gouv.fr/regions"), true);

        return $this->render('bird\repertory.html.twig',
            array(
                'birds' => $birds, 
                'nbRepertoryPages' => $nbRepertoryPages, 
                'nextPage' => $nextPage, 
                'previousPage' => $previousPage, '
                page' => $page, 
                'letter' => $letter, 
                'regions' => $regions,
            )); 
    }

    /**
     * @Route("repertoire/{page}", defaults={"page"=1}, requirements={"page" = "\d+"}, name="repertory")
     * @param Request $request
     * @param NAOBirdManager $naoBirdManager
     * @param NAOPagination $naoPagination
     * @param NAOCountBirds $naoCountBirds
     * @param $page
     * @return Response
     */
    public function showRepertory(Request $request, NAOBirdManager $naoBirdManager, NAOPagination $naoPagination, NAOCountBirds $naoCountBirds, $page)
    {
        $regions = json_decode(file_get_contents("https://geo.api.gouv.fr/regions"), true);

        $numberOfBirds = $naoCountBirds->countBirds();
        $numberOfBirdsPerPage = $naoPagination->getNbBirdsPerPage();
        $birds = $naoBirdManager->getBirdsPerPage($page, $numberOfBirds, $numberOfBirdsPerPage);
        $nbRepertoryPages = $naoPagination->CountNbPages($numberOfBirds, $numberOfBirdsPerPage);
        $nextPage = $naoPagination->getNextPage($page);
        $previousPage = $naoPagination->getPreviousPage($page);
        if ($request->isMethod('POST')) {
            $region = $request->get('region');
            return $this->redirectToRoute('result_search_birds', array('region' => $region,));
        }

        return $this->render('bird\repertory.html.twig',
            array(
                'birds' => $birds, 
                'nbRepertoryPages' => $nbRepertoryPages, 
                'nextPage' => $nextPage, 
                'previousPage' => $previousPage, 
                'page' => $page, 
                'regions' => $regions,
            )); 
    }

    /**
     * @Route("resultat-recherche-oiseaux/{region}/{page}", defaults={"page"=1}, requirements={"page" = "\d+"}, name="result_search_birds")
     * @param NAOBirdManager $naoBirdManager
     * @param NAOPagination $naoPagination
     * @param NAOCountBirds $naoCountBirds
     * @param $page
     * @param $region
     * @return Response
     */
    public function showBirdsByRegion(NAOBirdManager $naoBirdManager, NAOPagination $naoPagination, NAOCountBirds $naoCountBirds, $page, $region)
    {
        $regions = json_decode(file_get_contents("https://geo.api.gouv.fr/regions"), true);
        $numberOfSearchBirds = $naoCountBirds->countSearchBirdsByRegion($region);
        $numberOfBirdsPerPage = $naoPagination->getNbBirdsPerPage();
        $birds = $naoBirdManager->searchBirdsByRegionPerPage($region, $page, $numberOfSearchBirds, $numberOfBirdsPerPage);
        $nbRepertoryPages = $naoPagination->CountNbPages($numberOfSearchBirds, $numberOfBirdsPerPage);
        $nextPage = $naoPagination->getNextPage($page);
        $previousPage = $naoPagination->getPreviousPage($page);

        return $this->render('bird\repertory.html.twig',
            array
            (
                'birds' => $birds, 
                'nbRepertoryPages' => $nbRepertoryPages, 
                'nextPage' => $nextPage, 
                'previousPage' => $previousPage, 
                'page' => $page, 
                'regions' => $regions, 
                'region' => $region
            )); 
    }

    /**
     * @Route("oiseau/{id}", requirements={"id" = "\d+"}, name="bird")
     * @ParamConverter("bird", class="App\Entity\Bird")
     * @param $bird
     * @return Response
     */
    public function showBird(Bird $bird)
    {
        if (!$bird) {
            throw $this->createNotFoundException("Oiseau non trouvé...");
        }

        return $this->render('bird\bird.html.twig', array('bird' => $bird));
    }
}

templates/bird/bird.html.twig
{% extends "layout.html.twig" %}

{% block title %}{% if bird.vernacularname == false %}{{ bird.validname }} {% else %} {{ bird.vernacularname }} {% endif %}{% endblock %}
{% block mapStylesheets %} 
	{{ parent() }}
	<style type="text/css">
			#map{ /* la carte DOIT avoir une hauteur sinon elle n'apparaît pas */
				height:400px;
			}
		</style>
{% endblock %}

{% block body %}
	<div id="map" data-identifiant={{ bird.id }}>
	</div>
	<section>
		<h1>{% if bird.vernacularname == false %}{{ bird.validname }} {% else %} {{ bird.vernacularname }} - {{ bird.validname }}{% endif %}</h1>
		<p>{{ bird.image }}</p>
		<p>Règne : {{ bird.reign }}</p>
		<p>Classe : {{ bird.class }}</p>
		<p>Ordre : {{ bird.birdOrder }}</p>
		<p>Famille : {{ bird.family }}</p>
	</section>
{% endblock %}

{% block mapJavascripts %}
	{{ parent() }}
	<script type="text/javascript" src="{{ asset('javascript/maps/showmap.js') }}"></script>
{% endblock %}

templates/bird/repertory.html.twig
{% extends "layout.html.twig" %}

{% block title %} Répertoire {% endblock %}

{% block body %}
	<h1>Répertoire</h1>
	<section>
		{% set repositoryLetter = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'] %}
		<p>
			<a href="{{ path('repertory') }}">All</a> {% for i in 0..25 %} | <a href="{{ path('repertory_by_letter', {letter: repositoryLetter[i]}) }}">{{repositoryLetter[i]}}</a> {% endfor %}
		</p>
		<form action="{{ path('repertory') }}" method="post">
		<select name="region" id="region">
			<option disabled selected value="">Région</option>
            {% for region in regions %}
				<option value="{{ region.nom|lower }}">{{ region.nom }}</option>
            {% endfor %}
		</select>
		<button type="submit">Rechercher</button>
	</form>
	</section>
	{% for bird in birds %}
		<div>
			<p>{{ bird.image }}</p>
			<p><a href="{{ path('bird', {id: bird.id}) }}">{% if bird.vernacularname == false %}{{ bird.validname }} {% else %} {{ bird.vernacularname }} - {{ bird.validname }}</a>{% endif %}</p>
		</div>
	{% endfor %}
		<div>
			<ul>
				{% if nbRepertoryPages  > 1 %}
					{% if previousPage > 0 %}
					<p> 
						{% if letter is defined %}
							<a href="/repertoire/{{letter}}/{{previousPage}}"> << </a> 
						{% elseif region is defined  %}
							<a href="/resultat-recherche-oiseaux/{{region}}/{{previousPage}}"> << </a> 
						{% else %}
							<a href="/repertoire/{{previousPage}}"> << </a> 
						{% endif %}
					</p>
				{% endif %}
				{% for i in 1..nbRepertoryPages %}
					<li {% if page == i %} class="active" {% endif %}>
						{% if letter is defined %}
   							<a href="/repertoire/{{letter}}/{{i}}"> {{i}} </a>
   						{% elseif region is defined  %}
							<a href="/resultat-recherche-oiseaux/{{region}}/{{i}}"> {{i}} </a> 
   						{% else %}
							<a href="/repertoire/{{i}}"> {{i}} </a> 
						{% endif %}
	   				</li>
	   			{% endfor %}
	    		<p>
	    			{% if nextPage <= nbRepertoryPages %}
	    				{% if letter is defined %}
	    					<a href="/repertoire/{{letter}}/{{nextPage}}"> >> </a>
	    					{% elseif region is defined  %}
							<a href="/resultat-recherche-oiseaux/{{region}}/{{nextPage}}"> >> </a> 
    					{% else %}
							<a href="/repertoire/{{nextPage}}"> >> </a> 
						{% endif %}
	   				{% endif %}
	   			</p> 
	   		{% endif %}
		</ul>
	</div>
{% endblock %}

{% block javascripts %}{% endblock %}